version: "3.4"
networks:
  notka:
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "6543:1433"
    environment:
      SA_PASSWORD: "admin_123"
      ACCEPT_EULA: "Y"
    networks:
      - notka

  app_api:
    build:
      context: .
      dockerfile: InPostApp/Server/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql
    networks:
      - notka
